#if USE_YARN3

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PixelCrushersYarnSpinnerParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace PixelCrushers.DialogueSystem.Yarn3 {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPixelCrushersYarnSpinnerParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
//[System.CLSCompliant(false)]
public partial class PixelCrushersYarnSpinnerParserBaseListener : IPixelCrushersYarnSpinnerParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.dialogue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDialogue([NotNull] PixelCrushersYarnSpinnerParser.DialogueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.dialogue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDialogue([NotNull] PixelCrushersYarnSpinnerParser.DialogueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.file_hashtag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile_hashtag([NotNull] PixelCrushersYarnSpinnerParser.File_hashtagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.file_hashtag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile_hashtag([NotNull] PixelCrushersYarnSpinnerParser.File_hashtagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNode([NotNull] PixelCrushersYarnSpinnerParser.NodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNode([NotNull] PixelCrushersYarnSpinnerParser.NodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.title_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTitle_header([NotNull] PixelCrushersYarnSpinnerParser.Title_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.title_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTitle_header([NotNull] PixelCrushersYarnSpinnerParser.Title_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.when_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhen_header([NotNull] PixelCrushersYarnSpinnerParser.When_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.when_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhen_header([NotNull] PixelCrushersYarnSpinnerParser.When_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeader([NotNull] PixelCrushersYarnSpinnerParser.HeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeader([NotNull] PixelCrushersYarnSpinnerParser.HeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.header_when_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeader_when_expression([NotNull] PixelCrushersYarnSpinnerParser.Header_when_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.header_when_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeader_when_expression([NotNull] PixelCrushersYarnSpinnerParser.Header_when_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] PixelCrushersYarnSpinnerParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] PixelCrushersYarnSpinnerParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] PixelCrushersYarnSpinnerParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] PixelCrushersYarnSpinnerParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_statement([NotNull] PixelCrushersYarnSpinnerParser.Line_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_statement([NotNull] PixelCrushersYarnSpinnerParser.Line_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_formatted_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Line_formatted_textContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_formatted_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Line_formatted_textContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.hashtag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashtag([NotNull] PixelCrushersYarnSpinnerParser.HashtagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.hashtag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashtag([NotNull] PixelCrushersYarnSpinnerParser.HashtagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineCondition</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.line_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineCondition([NotNull] PixelCrushersYarnSpinnerParser.LineConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineCondition</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.line_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineCondition([NotNull] PixelCrushersYarnSpinnerParser.LineConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineOnceCondition</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.line_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineOnceCondition([NotNull] PixelCrushersYarnSpinnerParser.LineOnceConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineOnceCondition</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.line_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineOnceCondition([NotNull] PixelCrushersYarnSpinnerParser.LineOnceConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expParens</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpParens([NotNull] PixelCrushersYarnSpinnerParser.ExpParensContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expParens</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpParens([NotNull] PixelCrushersYarnSpinnerParser.ExpParensContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expMultDivMod</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpMultDivMod([NotNull] PixelCrushersYarnSpinnerParser.ExpMultDivModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expMultDivMod</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpMultDivMod([NotNull] PixelCrushersYarnSpinnerParser.ExpMultDivModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expComparison</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpComparison([NotNull] PixelCrushersYarnSpinnerParser.ExpComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expComparison</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpComparison([NotNull] PixelCrushersYarnSpinnerParser.ExpComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expNegative</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpNegative([NotNull] PixelCrushersYarnSpinnerParser.ExpNegativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expNegative</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpNegative([NotNull] PixelCrushersYarnSpinnerParser.ExpNegativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expAndOrXor</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpAndOrXor([NotNull] PixelCrushersYarnSpinnerParser.ExpAndOrXorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expAndOrXor</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpAndOrXor([NotNull] PixelCrushersYarnSpinnerParser.ExpAndOrXorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expAddSub</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpAddSub([NotNull] PixelCrushersYarnSpinnerParser.ExpAddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expAddSub</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpAddSub([NotNull] PixelCrushersYarnSpinnerParser.ExpAddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expNot</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpNot([NotNull] PixelCrushersYarnSpinnerParser.ExpNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expNot</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpNot([NotNull] PixelCrushersYarnSpinnerParser.ExpNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expValue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpValue([NotNull] PixelCrushersYarnSpinnerParser.ExpValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expValue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpValue([NotNull] PixelCrushersYarnSpinnerParser.ExpValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expEquality</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpEquality([NotNull] PixelCrushersYarnSpinnerParser.ExpEqualityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expEquality</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpEquality([NotNull] PixelCrushersYarnSpinnerParser.ExpEqualityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueNumber([NotNull] PixelCrushersYarnSpinnerParser.ValueNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueNumber([NotNull] PixelCrushersYarnSpinnerParser.ValueNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTrue([NotNull] PixelCrushersYarnSpinnerParser.ValueTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTrue([NotNull] PixelCrushersYarnSpinnerParser.ValueTrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueFalse([NotNull] PixelCrushersYarnSpinnerParser.ValueFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueFalse([NotNull] PixelCrushersYarnSpinnerParser.ValueFalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueVar</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueVar([NotNull] PixelCrushersYarnSpinnerParser.ValueVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueVar</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueVar([NotNull] PixelCrushersYarnSpinnerParser.ValueVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueString([NotNull] PixelCrushersYarnSpinnerParser.ValueStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueString([NotNull] PixelCrushersYarnSpinnerParser.ValueStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFunc</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueFunc([NotNull] PixelCrushersYarnSpinnerParser.ValueFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFunc</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueFunc([NotNull] PixelCrushersYarnSpinnerParser.ValueFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTypeMemberReference</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTypeMemberReference([NotNull] PixelCrushersYarnSpinnerParser.ValueTypeMemberReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTypeMemberReference</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTypeMemberReference([NotNull] PixelCrushersYarnSpinnerParser.ValueTypeMemberReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] PixelCrushersYarnSpinnerParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] PixelCrushersYarnSpinnerParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call([NotNull] PixelCrushersYarnSpinnerParser.Function_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call([NotNull] PixelCrushersYarnSpinnerParser.Function_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.typeMemberReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeMemberReference([NotNull] PixelCrushersYarnSpinnerParser.TypeMemberReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.typeMemberReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeMemberReference([NotNull] PixelCrushersYarnSpinnerParser.TypeMemberReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] PixelCrushersYarnSpinnerParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] PixelCrushersYarnSpinnerParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_clause([NotNull] PixelCrushersYarnSpinnerParser.If_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_clause([NotNull] PixelCrushersYarnSpinnerParser.If_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_if_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_if_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_if_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_if_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.set_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_statement([NotNull] PixelCrushersYarnSpinnerParser.Set_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.set_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_statement([NotNull] PixelCrushersYarnSpinnerParser.Set_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.call_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_statement([NotNull] PixelCrushersYarnSpinnerParser.Call_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.call_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_statement([NotNull] PixelCrushersYarnSpinnerParser.Call_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand_statement([NotNull] PixelCrushersYarnSpinnerParser.Command_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand_statement([NotNull] PixelCrushersYarnSpinnerParser.Command_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_formatted_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Command_formatted_textContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_formatted_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Command_formatted_textContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShortcut_option_statement([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_option_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShortcut_option_statement([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_option_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShortcut_option([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_optionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShortcut_option([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_optionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_group_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_group_statement([NotNull] PixelCrushersYarnSpinnerParser.Line_group_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_group_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_group_statement([NotNull] PixelCrushersYarnSpinnerParser.Line_group_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_group_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_group_item([NotNull] PixelCrushersYarnSpinnerParser.Line_group_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_group_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_group_item([NotNull] PixelCrushersYarnSpinnerParser.Line_group_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.declare_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare_statement([NotNull] PixelCrushersYarnSpinnerParser.Declare_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.declare_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare_statement([NotNull] PixelCrushersYarnSpinnerParser.Declare_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.enum_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_statement([NotNull] PixelCrushersYarnSpinnerParser.Enum_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.enum_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_statement([NotNull] PixelCrushersYarnSpinnerParser.Enum_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.enum_case_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_case_statement([NotNull] PixelCrushersYarnSpinnerParser.Enum_case_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.enum_case_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_case_statement([NotNull] PixelCrushersYarnSpinnerParser.Enum_case_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>jumpToNodeName</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpToNodeName([NotNull] PixelCrushersYarnSpinnerParser.JumpToNodeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>jumpToNodeName</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpToNodeName([NotNull] PixelCrushersYarnSpinnerParser.JumpToNodeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>jumpToExpression</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpToExpression([NotNull] PixelCrushersYarnSpinnerParser.JumpToExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>jumpToExpression</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpToExpression([NotNull] PixelCrushersYarnSpinnerParser.JumpToExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>detourToNodeName</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDetourToNodeName([NotNull] PixelCrushersYarnSpinnerParser.DetourToNodeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>detourToNodeName</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDetourToNodeName([NotNull] PixelCrushersYarnSpinnerParser.DetourToNodeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>detourToExpression</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDetourToExpression([NotNull] PixelCrushersYarnSpinnerParser.DetourToExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>detourToExpression</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDetourToExpression([NotNull] PixelCrushersYarnSpinnerParser.DetourToExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] PixelCrushersYarnSpinnerParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] PixelCrushersYarnSpinnerParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.once_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnce_statement([NotNull] PixelCrushersYarnSpinnerParser.Once_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.once_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnce_statement([NotNull] PixelCrushersYarnSpinnerParser.Once_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.once_primary_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnce_primary_clause([NotNull] PixelCrushersYarnSpinnerParser.Once_primary_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.once_primary_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnce_primary_clause([NotNull] PixelCrushersYarnSpinnerParser.Once_primary_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.once_alternate_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnce_alternate_clause([NotNull] PixelCrushersYarnSpinnerParser.Once_alternate_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.once_alternate_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnce_alternate_clause([NotNull] PixelCrushersYarnSpinnerParser.Once_alternate_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.structured_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructured_command([NotNull] PixelCrushersYarnSpinnerParser.Structured_commandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.structured_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructured_command([NotNull] PixelCrushersYarnSpinnerParser.Structured_commandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.structured_command_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructured_command_value([NotNull] PixelCrushersYarnSpinnerParser.Structured_command_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.structured_command_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructured_command_value([NotNull] PixelCrushersYarnSpinnerParser.Structured_command_valueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace PixelCrushers.DialogueSystem.Yarn3

#endif
